version: "3.3"

services:

  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3382:3382
    environment:
      PUBLIC_URL: "http://localhost:3382/synth/v1/files"
      ROOT_URL: "http://localhost:3382/synth/v1"
    env_file: .env
    command: yarn start
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  # NB: if you don't want to test with minio, start only api container
  # docker-compose up api
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: S3_ACCESS_KEY
      MINIO_SECRET_KEY: S3_SECRET_KEY
    ports:
    # http://localhost:3383/
    - "3383:9000"
    command:
    - server
    - /export
