version: "3.3"

services:

  api:
    build: .
    volumes:
      - ./public:/app/public
    ports:
      - 3382:3382
    environment:
      - PUBLIC_URL=http://synthproxy.example.net/synth/v1/files
    labels:
      traefik.frontend.rule: "Host:synthproxy.example.net"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
