version: "3.3"

services:

  api:
    build: .
    volumes:
      - ./public:/app/public
    ports:
      - 3382:3382
    environment:
      - PUBLIC_URL=http://volgin.delfi.lan:3381
    labels:
      traefik.frontend.rule: "Host:eki-tts.reviewapp.internal.lan"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
